# Auto-assign configuration
# Set assignees and reviewers for pull requests and issues

# Assignees for pull requests
addAssignees: author

# Reviewers for pull requests
# Update with actual GitHub usernames of maintainers
addReviewers: false
# Uncomment and add actual maintainer usernames to enable
# reviewers:
#   - maintainer-username-1
#   - maintainer-username-2

# Number of reviewers to assign
numberOfReviewers: 1

# Skip keywords in PR title to avoid auto-assignment
skipKeywords:
  - wip
  - WIP
  - draft

# Assignees for issues
# Update with actual GitHub usernames of maintainers
addIssueAssignees: false
# Uncomment and add actual maintainer usernames to enable
# issueAssignees:
#   - maintainer-username-1
#   - maintainer-username-2

# Number of issue assignees
numberOfIssueAssignees: 1
