# Auto-labeling configuration for pull requests
# Add labels based on files changed

documentation:
  - '**/*.md'
  - 'docs/**/*'

dependencies:
  - 'package.json'
  - 'package-lock.json'

type:ci/cd:
  - '.github/workflows/**/*'
  - '.github/dependabot.yml'

type:test:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - 'src/setupTests.ts'

type:feature:
  - 'src/components/**/*'
  - 'src/hooks/**/*'

type:refactor:
  - 'src/**/*.tsx'
  - 'src/**/*.ts'

style:
  - '**/*.css'
  - 'tailwind.config.js'
  - 'postcss.config.js'
