# Auto-labeling configuration for pull requests
# Add labels based on files changed
# Format for actions/labeler@v5

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
  - changed-files:
    - any-glob-to-any-file: 'package-lock.json'

type:ci/cd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'
  - changed-files:
    - any-glob-to-any-file: '.github/dependabot.yml'

type:test:
  - changed-files:
    - any-glob-to-any-file: '**/*.test.ts'
  - changed-files:
    - any-glob-to-any-file: '**/*.test.tsx'
  - changed-files:
    - any-glob-to-any-file: '**/*.spec.ts'
  - changed-files:
    - any-glob-to-any-file: '**/*.spec.tsx'
  - changed-files:
    - any-glob-to-any-file: 'src/setupTests.ts'

type:feature:
  - changed-files:
    - any-glob-to-any-file: 'src/components/**/*'
  - changed-files:
    - any-glob-to-any-file: 'src/hooks/**/*'

type:refactor:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*.tsx'
  - changed-files:
    - any-glob-to-any-file: 'src/**/*.ts'

style:
  - changed-files:
    - any-glob-to-any-file: '**/*.css'
  - changed-files:
    - any-glob-to-any-file: 'tailwind.config.js'
  - changed-files:
    - any-glob-to-any-file: 'postcss.config.js'
