- name: bug
  color: d73a4a
  description: Something isn't working

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: question
  color: d876e3
  description: Further information is requested

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: priority:high
  color: b60205
  description: High priority

- name: priority:medium
  color: fbca04
  description: Medium priority

- name: priority:low
  color: 0e8a16
  description: Low priority

- name: status:in-progress
  color: ededed
  description: Currently being worked on

- name: status:blocked
  color: d93f0b
  description: Blocked by another issue or dependency

- name: type:bug
  color: d73a4a
  description: Bug or defect

- name: type:feature
  color: a2eeef
  description: New feature

- name: type:refactor
  color: fbca04
  description: Code refactoring

- name: type:test
  color: 1d76db
  description: Testing related

- name: type:ci/cd
  color: 000000
  description: CI/CD related

- name: triage
  color: fef2c0
  description: Needs triage

- name: stale
  color: eeeeee
  description: Stale issue or PR

- name: security
  color: ee0701
  description: Security related

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file
