# Auto-labeling configuration for pull requests
# Add labels based on files changed
# Format for actions/labeler@v5
#
# Note: Multiple labels can (and should) be applied to the same PR.
# For example, updating package.json will get both 'dependencies' and 'type:build' labels.
# This is intentional to provide comprehensive categorization.

# ============================================
# DOCUMENTATION LABELS
# ============================================

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - '.github/*.md'
          - 'docs/**/*'

# ============================================
# DEPENDENCY LABELS
# ============================================

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'yarn.lock'
          - 'pnpm-lock.yaml'

# ============================================
# CI/CD AND WORKFLOW LABELS
# Note: vercel.json also appears in type:build for deployment context
# ============================================

type:ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**/*'
          - '.github/dependabot.yml'
          - '.github/auto-assign.yml'
          - 'vercel.json'

# ============================================
# TESTING LABELS
# ============================================

type:test:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.test.tsx'
          - '**/*.spec.ts'
          - '**/*.spec.tsx'
          - 'src/setupTests.ts'
          - 'src/App.test.tsx'

# ============================================
# FEATURE LABELS (Components, Hooks, Data)
# ============================================

type:feature:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**/*.tsx'
          - 'src/hooks/**/*.ts'
          - 'src/data/**/*.ts'
          - 'src/icons/**/*.tsx'

# ============================================
# STYLING LABELS
# ============================================

style:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.css'
          - 'tailwind.config.js'
          - 'postcss.config.js'
          - 'postcss.config.js'
          - '.prettierrc.json'
          - '.prettierignore'

# ============================================
# CONFIGURATION LABELS
# ============================================

type:config:
  - changed-files:
      - any-glob-to-any-file:
          - 'tsconfig.json'
          - '.env.example'
          - '.gitignore'
          - '.lycheeignore'
          - '**/*.config.js'
          - '**/*.config.ts'
          - '.github/labels.yml'
          - '.github/labeler.yml'

# ============================================
# BUILD AND DEPLOYMENT LABELS
# Note: vercel.json and package.json also appear in other labels
# This overlap is intentional for comprehensive categorization
# ============================================

type:build:
  - changed-files:
      - any-glob-to-any-file:
          - 'vercel.json'
          - 'package.json'
          - 'tsconfig.json'
          - 'webpack.config.js'
          - 'rollup.config.js'
          - 'vite.config.js'

# ============================================
# PUBLIC/ASSETS LABELS
# ============================================

type:assets:
  - changed-files:
      - any-glob-to-any-file:
          - 'public/**/*'
          - '**/*.png'
          - '**/*.jpg'
          - '**/*.jpeg'
          - '**/*.gif'
          - '**/*.svg'
          - '**/*.ico'
          - '**/*.webp'

# ============================================
# SECURITY LABELS
# ============================================

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - '.github/workflows/codeql.yml'
          - '.github/workflows/dependency-review.yml'

# ============================================
# ROOT LEVEL IMPORTANT FILES
# ============================================

type:meta:
  - changed-files:
      - any-glob-to-any-file:
          - 'LICENSE'
          - 'CODE_OF_CONDUCT.md'
          - 'CONTRIBUTING.md'
          - 'AUTHORS.md'
          - 'CHANGELOG.md'

# ============================================
# APPLICATION CORE (App.tsx, index.tsx, routing)
# ============================================

type:core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/App.tsx'
          - 'src/index.tsx'
          - 'src/App.css'
          - 'src/index.css'
          - 'src/react-app-env.d.ts'
          - 'src/reportWebVitals.ts'

# ============================================
# SEO AND SITEMAP
# ============================================

type:seo:
  - changed-files:
      - any-glob-to-any-file:
          - 'public/sitemap.xml'
          - 'public/robots.txt'
          - 'SEO_STRATEGY.md'
          - 'public/manifest.json'

# ============================================
# SPECIFIC COMPONENT TYPES
# Note: These are specific core UI components that are frequently modified
# Add new important UI components here as needed
# ============================================

type:ui-component:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/NavigationBar.tsx'
          - 'src/components/Footer.tsx'
          - 'src/components/HeroSection.tsx'
          - 'src/components/LoadingSpinner.tsx'
          - 'src/components/ErrorBoundary.tsx'

type:page-component:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/*Page.tsx'
          - 'src/components/PageLayout.tsx'

type:form-component:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/*Form.tsx'

# ============================================
# ACCESSIBILITY AND PERFORMANCE
# ============================================

type:accessibility:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/hooks/useAccessibility.ts'
          - 'src/components/SkipToMain.tsx'

type:performance:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/hooks/usePerformanceMonitoring.ts'
          - 'src/reportWebVitals.ts'

# ============================================
# REFACTOR LABEL
# Applies to TypeScript changes (may overlap with other labels)
# Multiple labels can be applied to the same PR
# ============================================

type:refactor:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.ts'
          - 'src/**/*.tsx'
