# Auto-labeling configuration for pull requests
# Add labels based on files changed
# Format for actions/labeler@v5

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'

type:ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/dependabot.yml'

type:test:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - 'src/setupTests.ts'

type:feature:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/components/**/*'
      - 'src/hooks/**/*'

type:refactor:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*.tsx'
      - 'src/**/*.ts'

style:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - 'tailwind.config.js'
      - 'postcss.config.js'
